
name: My-GitHubActions-Basics

on: 
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:       
      
    - name: List current folder
      run : ls -la
   
    - name: Git clone my repo
      uses: actions/checkout@v2  
  
    - name: List current folder
      run : ls -la
  
  
