
name: My-GitHubActions-Basics

on:
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
      
    - name: Install oci-cli
      uses: bytesbay/oci-cli-action@v1.0.2
      with:
        user: "${{ secrets.OCI_USER }}"
        fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
        tenancy: "${{ secrets.OCI_TENANCY }}"
        region: "${{ secrets.OCI_REGION }}"
        api_key: |
          ${{ secrets.OCI_API_KEY }}
        verbose: true
    
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/ubuntu/back_web"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo mv ~/back_web/* /var/www/html/ 
    
              
    
  
  
