
name: My-GitHubActions-Basics

env:
  
  
  DEPLOY_PACKAGE_NAME       : "back_web_${{ github.sha }}.zip"
  
on: 
  push:
    branches: 
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
       
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: List current folder
      run : ls -la
              
    
  
  
